### ISSUE TITLE
Internationalization and localization

### ISSUE THREAD

**Issue by Ubugeeei** [oxc-project/oxc-project.github.io#13]
# Roadmap
- [x] Create a framework for i18n support (for now, keep all content in English) 👉 #27
- [ ] Translation of existing documents
  As for the Japanese, either @Ubugeeei  or @NozomuIkuta  will handle it.
- [x] Move [javascript-parser-in-rust.](https://github.com/oxc-project/javascript-parser-in-rust)
  Let's think about the details [here](https://github.com/oxc-project/oxc-project.github.io/issues/4).
- [ ] Decide on the handling of the [javascript-parser-in-rust repository](https://github.com/oxc-project/javascript-parser-in-rust) in consultation with @Boshen .
- [ ] Consider the operational approach for translations of this repository and document it in the contribution guide.

**Comment by NozomuIkuta** [comment]
@Ubugeeei 

Thank you for creating this issue.

Introducing i18n into the current site is not so difficult.
Actually, VitePress default theme supports it natively, and I could set it up within 30 minutes.

All we have to do is to define `docs/<locale>` directory (e.g. `docs/ja`) and put same files as ones at root directory (e.g. `docs/index.md` corresponds to `docs/ja/index.md`).

The biggest issue of supporting i18n is how we manage translation, which is likely to be behind the original version.
As far as I know, [Vue Router's practice](https://github.com/vuejs/router/blob/main/.github/contributing.md#contributing-docs) is one of successful cases.

Without operation policy, supporting multi language will lead to management difficulty and user confusion.

If we could manage translated-versions in other repositories (although we need another domain for that), [vuejs-translations/ryu-cho](https://github.com/vuejs-translations/ryu-cho) would help us to track differences between translated version and the original one.

If we can coma up with a systematic way of tracking changes on the original version in one repository, we can immediately start i18n support, or we could consider the details later and just complete #4.

Do you have any thoughts?

**Comment by Ubugeeei** [comment]
Hmm, this is a difficult issue.
I don't have any ideas at the moment, but for now, 
let's look for and refer to some projects that are being operated within the same domain (the same repository) 😕

**Comment by Ubugeeei** [comment]
- [vue-i18n](https://kazupon.github.io/vue-i18n/)
- [pinia (only zh)](https://pinia.vuejs.org/)
- [vue router (only zh)](https://router.vuejs.org/)
- [vuex](https://vuex.vuejs.org/ja/)
- [vue macros](https://vue-macros.dev/)
- [vuetify](https://vuetifyjs.com/en/)

**Comment by Ubugeeei** [comment]
@NozomuIkuta 

I personally have a preference for operating within the same repository. 
Similar to how vue router created the docs-sync-zh, I think creating branches for each locale in the same repository could be a good idea.
 I'll leave the naming of the branches up to you. 😉

**Comment by Ubugeeei** [comment]
@NozomuIkuta 
I have documented the [roadmap](https://github.com/oxc-project/oxc-project.github.io/issues/13#issue-2000806715).
There are challenges regarding operations, but let's tackle them gradually.

**Comment by NozomuIkuta** [comment]
> > Decide on the handling of the [javascript-parser-in-rust repository](https://github.com/oxc-project/javascript-parser-in-rust) in consultation with @Boshen .
> 
> Shall we copy all content into the "learn" section once i18n support is landed?

I wonder where to insert the contents in "Learn" section 🤔 
Current sidebar is like below:

- Architecture
  - Introduction
  - Parser
  - Linter
  - Resolver
  - Transformer
  - Formatter
  - Minifier
- ECMAScript
  - Spec
  - Grammer
- Performance
- Ecosystem
- References

Shall we add top-level category like "JavaScript Parser in Rust" or add contents to ECMAScript category?

**Comment by NozomuIkuta** [comment]
VitePress author (thank you @brc-dd) shares it with me [Crowdin](https://crowdin.com/) as an option for translation management. 

You can try it out in [use case of pnpm](https://crowdin.com/project/pnpm).

They support free plan for OSS projects ([link](https://crowdin.com/page/open-source-project-setup-request)), so if the service matches our needs, @Boshen can apply for it.

**Comment by Boshen** [comment]
> VitePress author (thank you @brc-dd) shares it with me [Crowdin](https://crowdin.com/) as an option for translation management.
> 
> You can try it out in [use case of pnpm](https://crowdin.com/project/pnpm).
> 
> They support free plan for OSS projects ([link](https://crowdin.com/page/open-source-project-setup-request)), so if the service matches our needs, @Boshen can apply for it.

I've applied it with the following message 

> oxc (The JavaScript Oxdiation Compiler) is a collection of JavaScript tools written in Rust.
> Oxc is building a parser, linter, formatter, transpiler, minifier, resolver ... all written in Rust.
> The website will eventually contain information around how to use, contribute and learn everything around the oxc project.
> The website is currently using Vitepress and we are exploring translation management tracked at https://github.com/oxc-project/oxc-project.github.io/issues/13

Let's hope they accept the application 🤞

**Comment by Boshen** [comment]
Everything seems to be ready, there is now a github branch https://github.com/oxc-project/oxc-project.github.io/commits/l10n_main 🤔

**Comment by Boshen** [comment]
It seems like Crowndin is working now, let's play around with it by moving contents of [javascript-parser-in-rust repository](https://github.com/oxc-project/javascript-parser-in-rust) over.

**Comment by NozomuIkuta** [comment]
@Boshen 

I'm translating Japanese document and want to test Crowdin config like path matching.
Would you give me and @Ubugeeei a role with which we can synchronize Japanese contents (I gues Manager role?)?
This is also about testing fix for https://github.com/oxc-project/oxc-project.github.io/pull/50#issuecomment-1837535104 🙏

**Comment by Boshen** [comment]
> @Boshen
> 
> I'm translating Japanese document and want to test Crowdin config like path matching. Would you give me and @Ubugeeei a role with which we can synchronize Japanese contents (I gues Manager role?)? This is also about testing fix for [#50 (comment)](https://github.com/oxc-project/oxc-project.github.io/pull/50#issuecomment-1837535104) 🙏

![image](https://github.com/oxc-project/oxc-project.github.io/assets/1430279/28f5b425-4501-4fc8-8c49-167e798228c5)

This is unfortunate. What's required in order to make things work? I'll configure it.

**Comment by brc-dd** [comment]
Shouldn't the limit for open-source projects be more? 60K words is for free accounts. You can probably ask their support. Or are you logging in from some different email? 👀

**Comment by NozomuIkuta** [comment]
@Boshen 

I'm glad to hear that they approved your request 👍 

By the way, now is it possible to manage roles in the project, or do we have to upgrade plan?

**Comment by NozomuIkuta** [comment]
Hmm, it says that "[Crowdin is completely free of charge for open-source projects](https://crowdin.com/page/open-source-project-setup-request)". 🤔 

You might want to contact them again for support.

**Comment by Boshen** [comment]
> Hmm, it says that "[Crowdin is completely free of charge for open-source projects](https://crowdin.com/page/open-source-project-setup-request)". 🤔
> 
> You might want to contact them again for support.

I guess it's free but the tier only allows for 1 manager. We can have as many translators as we want though.

**Comment by Boshen** [comment]
Thank you all for the effort for setting this up. I'm going to close as not planned for now due to maintenance burden, and avoiding burn out.
